# Generated by Django 6.0.3 on 2026-04-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
