# Generated by Django 6.0.3 on 2026-04-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_api', '0002_qrcode_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='qr_image',
            field=models.ImageField(blank=True, upload_to='qr_codes/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='redirect_url',
            field=models.URLField(default='https://www.google.com', help_text='Final URL opened after the tracking page records the scan.', max_length=2048),
        ),
    ]
