# Generated by Django 6.0.3 on 2026-04-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_api', '0005_qrcode_module_color_center_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='short_code',
            field=models.SlugField(help_text='Tracking link path: your site serves /s/<this value>/ (letters, numbers, hyphens, underscores). Change in admin to customize the URL; must stay unique.', max_length=16, unique=True),
        ),
    ]
